### ISSUE TITLE
Archiver not working in v1.18.6

### ISSUE THREAD

**Issue by MaxWaldorf** [julianlam/nodebb-plugin-archiver#8]
It used to work correctly in previous versions but now, it doesn't do anything...

Test works but run doesn't actually do anything on the DB...

Any way I can try to debug?

**Comment by MaxWaldorf** [comment]
Ok, I have a log now:

```
io: 1 on [ { type: 2, nsp: '/', id: 36, data: [ 'plugins.archiver.run', {} ] } ]
2021-11-22T14:41:19.744Z [4567/204] - error: uncaughtException: Cannot destructure property 'tid' of 'object null' as it is null.
TypeError: Cannot destructure property 'tid' of 'object null' as it is null.
    at /usr/src/app/node_modules/nodebb-plugin-archiver/index.js:118:36
    at /usr/src/app/src/promisify.js:43:50
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {"date":"Mon Nov 22 2021 14:41:19 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"os":{"loadavg":[1.64,1.72,1.67],"uptime":4756861.53},"process":{"argv":["/usr/local/bin/node","/usr/src/app/app.js"],"cwd":"/usr/src/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":19124337,"external":21796365,"heapTotal":191467520,"heapUsed":106664888,"rss":201875456},"pid":204,"uid":1000,"version":"v16.13.0"},"stack":"TypeError: Cannot destructure property 'tid' of 'object null' as it is null.\n    at /usr/src/app/node_modules/nodebb-plugin-archiver/index.js:118:36\n    at /usr/src/app/src/promisify.js:43:50\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","trace":[{"column":36,"file":"/usr/src/app/node_modules/nodebb-plugin-archiver/index.js","function":null,"line":118,"method":null,"native":false},{"column":50,"file":"/usr/src/app/src/promisify.js","function":null,"line":43,"method":null,"native":false},{"column":21,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":83,"method":null,"native":false}]}
2021-11-22T14:41:19.745Z [4567/204] - error: TypeError: Cannot destructure property 'tid' of 'object null' as it is null.
    at /usr/src/app/node_modules/nodebb-plugin-archiver/index.js:118:36
    at /usr/src/app/src/promisify.js:43:50
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2021-11-22T14:41:19.746Z [4567/204] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2021-11-22T14:41:19.755Z [4567/204] - info: [app] Web server closed to connections.
2021-11-22T14:41:19.762Z [4567/204] - error: uncaughtException: Cannot destructure property 'tid' of 'object null' as it is null.
TypeError: Cannot destructure property 'tid' of 'object null' as it is null.
    at /usr/src/app/node_modules/nodebb-plugin-archiver/index.js:118:36
    at /usr/src/app/src/promisify.js:43:50
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {"date":"Mon Nov 22 2021 14:41:19 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"os":{"loadavg":[1.64,1.72,1.67],"uptime":4756861.55},"process":{"argv":["/usr/local/bin/node","/usr/src/app/app.js"],"cwd":"/usr/src/app","execPath":"/usr/local/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":19125980,"external":21798048,"heapTotal":191467520,"heapUsed":107413480,"rss":202518528},"pid":204,"uid":1000,"version":"v16.13.0"},"stack":"TypeError: Cannot destructure property 'tid' of 'object null' as it is null.\n    at /usr/src/app/node_modules/nodebb-plugin-archiver/index.js:118:36\n    at /usr/src/app/src/promisify.js:43:50\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","trace":[{"column":36,"file":"/usr/src/app/node_modules/nodebb-plugin-archiver/index.js","function":null,"line":118,"method":null,"native":false},{"column":50,"file":"/usr/src/app/src/promisify.js","function":null,"line":43,"method":null,"native":false},{"column":21,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":83,"method":null,"native":false}]}
2021-11-22T14:41:19.763Z [4567/204] - error: TypeError: Cannot destructure property 'tid' of 'object null' as it is null.
    at /usr/src/app/node_modules/nodebb-plugin-archiver/index.js:118:36
    at /usr/src/app/src/promisify.js:43:50
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2021-11-22T14:41:19.763Z [4567/204] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2021-11-22T14:41:19.764Z [4567/204] - error: Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at new NodeError (node:internal/errors:371:5)
    at Server.close (node:net:1628:12)
    at Object.onceWrapper (node:events:509:28)
    at Server.emit (node:events:402:35)
    at Server.emit (node:domain:475:12)
    at emitCloseNT (node:net:1681:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[cluster] Child Process (204) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
```

**Comment by julianlam** [comment]
Hi @MaxWaldorf -- this looks related to a change from 5 months ago. Thanks for reporting, I'll add some additional checks to resolve.

**Comment by julianlam** [comment]
Can you please try with v5.0.1?

**Comment by julianlam** [comment]
Thanks for checking @MaxWaldorf !
